#!/usr/bin/python3
import os
import py_compile

pyfile = os.environ.get('PYFILE')
if pyfile:
    pycfile = pyfile + 'c'
    py_compile.compile(pyfile, pycfile)
    print(f"compiled {pyfile} to {pycfile}")
else:
    print("Environmental veriable not set")
